global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
  # - "first.rules"
  # - "second.rules"


# scrap self
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: app
    static_configs:
      - targets: ['app:3000']